// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hello": "Hello, World!",
  "Home": {
    "heroTitle": "Together, We",
    "heroSub": {
      "lead": "Lead",
      "achieve": "Achieve",
      "innovate": "Innovate"
    }
  }
};
export default messages;